### ISSUE TITLE
Cannot fetch time data from NTP

### ISSUE THREAD

**Issue by thematrixdev** [9seconds/mtg#161]
After a recently update on Ubuntu 20.04, my MTG-servers failed to start.
It said "Cannot fetch time data from NTP".

The NTP on the server seems to be working.

```
# ntpstat
synchronised to NTP server (133.243.238.163) at stratum 2 
   time correct to within 8 ms
   polling server every 64 s

```

```
# timedatectl
               Local time: Mon 2020-10-12 08:43:41 UTC
           Universal time: Mon 2020-10-12 08:43:41 UTC
                 RTC time: Mon 2020-10-12 08:43:42    
                Time zone: Etc/UTC (UTC, +0000)       
System clock synchronized: yes                        
              NTP service: n/a                        
          RTC in local TZ: no
```

docker-compose .yml
```
version: "3.8"
services:
  mtg-secured:
    container_name: mtg-secured
    image: nineseconds/mtg:latest
    environment:
      - MTG_IPV4=1.2.3.4:3128
    ports:
      - 3128:3128
    command: ["run", "dummy", "dummy"]
    restart: unless-stopped
  mtg-faketls:
    container_name: mtg-faketls
    image: nineseconds/mtg:latest
    environment:
      - MTG_BIND=0.0.0.0:443
      - MTG_IPV4=1.2.3.4:443
    ports:
      - 443:443
    command: ["run", "dummy", "dummy"]
    restart: unless-stopped
```

Thanks.
