### ISSUE TITLE
how to listen on both IPv4 and IPv6 adress? 

### ISSUE THREAD

**Issue by kobe-koto** [9seconds/mtg#308]
followed #298 but not working.

mtg version v2.1.7

this is my config:

```toml
secret = "7v...."
bind-to = ":58964"
````

I got this 

```
# mtg run /etc/mtg.toml
mtg: error: cannot init config: cannot parse config: cannot parse a config: empty host: :58964
```

and trying to listen on IPv6 only:

config:
```toml
secret = "7v..."
bind-to = "[::]:58964"
````

*it just runs, no output

and it does listening on IPv6
```sh
# netstat -tunlp | grep mtg
tcp6       0      0 :::58964                :::*                    LISTEN      102755/mtg  
```

and don't know why I cannot connect it through IPv6 but IPv4 works
