### ISSUE TITLE
Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol

### ISSUE THREAD

**Issue by subvillion** [9seconds/mtg#49]
```
version: '2'
services:
  mtg:
    image: nineseconds/mtg:latest
    restart: always
    ports:
     - "8848:8848/tcp"
    environment:
     - MTG_PORT=8848
    command: 4cf9XX44c
```
same with dd4cf9XX44c and mtg:stable, but it works for my apps, it's "old app" errors?
 
`mtg_1  | {"level":"error","ts":1540717142.1215146,"logger":"main","msg":"Cannot initialize client connection","connection_id":"f613f242-23b1-4508-8c47-94f2b408b2a8","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\ngithub.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\ngithub.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}
mtg_1  | {"level":"error","ts":1540717142.6385324,"logger":"main","msg":"Cannot initialize client connection","connection_id":"cba5e4ef-4286-454f-99ea-b4a071f6208a","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\ngithub.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\ngithub.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}`
